# baseURL = "http://example.org/"
languageCode = "en"
title = "Cloud Innovation Platform"
defaultContentLanguage= "en"
defaultContentLanguageInSubdir= true
[taxonomies]
  category = "categories"

[module]
  [[module.imports]]
    disable= false 
    path = "github.com/cip-core-mirrors/cip-core-portal-theme"